// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-ScRBuzjyoxo6wlydizByk2UCxvYXzI',
    appId: '1:766507839697:android:a2efb6c8e02aaddae295f0',
    messagingSenderId: '766507839697',
    projectId: 'madx-33e96',
    storageBucket: 'madx-33e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqWNIjFXAK9aVTDOcmWC5_6pv-fPgSTTg',
    appId: '1:766507839697:ios:f0a99ac63a3388f0e295f0',
    messagingSenderId: '766507839697',
    projectId: 'madx-33e96',
    storageBucket: 'madx-33e96.firebasestorage.app',
    androidClientId: '766507839697-9nts4eh9icecerbr95u85k9stggrmt8v.apps.googleusercontent.com',
    iosClientId: '766507839697-2d68md69l279c0rbocimrg9d2km0elea.apps.googleusercontent.com',
    iosBundleId: 'com.wesimplex.chapter',
  );

}