#!/usr/bin/env python3
import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

from pypdf import PdfReader

DATE_RE = re.compile(r"^(\d{1,2})/(\d{1,2})$")
TIME_RE = re.compile(r"(?:\d{1,2}:\d{2}\s?[AP]M|-)")
HEADER_RE = re.compile(r"^Generated by Blue Panda .* Page \d+ of \d+$")

# Common terms that are clearly part of event titles, not person names.
EVENT_WORDS = {
    "Accounting", "Administration", "Advertising", "Agribusiness", "AI", "Analysis",
    "Applications", "Banking", "Business", "Care", "Chain", "Communication",
    "Communications", "Community", "Computer", "Concepts", "Consumer", "Cyber",
    "Data", "Design", "Development", "Digital", "Economics", "Entrepreneurship",
    "Event", "Finance", "Financial", "Future", "Graphic", "Health", "Help",
    "Hospitality", "Human", "Impromptu", "Information", "Insurance", "International",
    "Introduction", "Journalism", "Law", "Leadership", "Management", "Marketing",
    "Media", "MIS", "Modeling", "Network", "Organizational", "Parliamentary",
    "Planning", "Presentation", "Procedure", "Production", "Project", "Public",
    "Real", "Resources", "Risk", "Sales", "Science", "Security", "Service",
    "Services", "Social", "Speaking", "Sports", "Statement", "Statistics",
    "Strategy", "Supply", "Systems", "Video", "Web", "Website", "Word", "Writing",
    "&", "and", "to", "of", "for", "the", "in", "I", "II", "III", "IV",
    "Prelim", "A", "B", "C", "D", "E"
}

NAME_PARTICLES = {
    "De", "Del", "La", "Le", "Di", "Da", "Dos", "Van", "Von", "St", "St.",
    "Mc", "Mac", "O'", "bin", "al"
}


def clean_line(line: str) -> str:
    return " ".join(line.replace("\u00a0", " ").split())


def normalize_time(token: str | None) -> str | None:
    if not token or token == "-":
        return None
    token = token.replace("AM", " AM").replace("PM", " PM") if " " not in token else token
    token = re.sub(r"\s+", " ", token).strip()
    return token


def normalize_date(mmdd: str, year: int) -> str:
    m = DATE_RE.match(mmdd)
    if not m:
        raise ValueError(f"Bad date token: {mmdd}")
    month, day = map(int, m.groups())
    return f"{year:04d}-{month:02d}-{day:02d}"


def looks_like_name_token(token: str) -> bool:
    if token in NAME_PARTICLES:
        return True
    if token in EVENT_WORDS:
        return False
    return bool(re.match(r"^[A-Z][A-Za-z.''-]*$", token))


def split_event_and_inline_name(before: str) -> tuple[str, str | None]:
    """
    Input is the text before the date on a row, which usually looks like:
      '<event title> <first student name>'
    but sometimes is just the event title.
    """
    tokens = before.split()
    if not tokens:
        return before, None

    best_idx = None
    for i in range(1, len(tokens)):
        left = tokens[:i]
        right = tokens[i:]
        if not right:
            continue
        if all(looks_like_name_token(tok) for tok in right):
            if left and left[-1] in {"-", "&"}:
                continue
            best_idx = i

    if best_idx is None:
        return before.strip(), None

    event = " ".join(tokens[:best_idx]).strip()
    inline_name = " ".join(tokens[best_idx:]).strip()

    first_name_token = inline_name.split()[0]
    if first_name_token in EVENT_WORDS:
        for i in range(best_idx + 1, len(tokens)):
            right = tokens[i:]
            if all(looks_like_name_token(tok) for tok in right) and right[0] not in EVENT_WORDS:
                return " ".join(tokens[:i]).strip(), " ".join(right).strip()
        return before.strip(), None

    return event, inline_name


TIME_LINE_RE = re.compile(r'^(.*?)(\d{1,2}:\d{2}\s?[AP]M(?:\s+\d{1,2}:\d{2}\s?[AP]M){1,2})\s*$')


def _extract_time_tokens(line: str) -> list[str]:
    return TIME_RE.findall(line)


def _split_names_and_times(line: str) -> tuple[str, list[str]]:
    match = TIME_LINE_RE.match(line)
    if match:
        prefix = match.group(1).strip()
        tokens = _extract_time_tokens(match.group(2))
        return prefix, tokens
    return line.strip(), []


MONTHS = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12,
}


def _parse_event_schedule_page(lines: list[str], year: int) -> tuple[str | None, list[dict]]:
    event_name = None
    location = None
    date = None
    for line in lines:
        if line.startswith("Event When:"):
            m = re.search(r"Event When:\s*\w+\s*-\s*([A-Za-z]+)\s+(\d{1,2})", line)
            if m:
                month_name = m.group(1).capitalize()
                day = int(m.group(2))
                month = MONTHS.get(month_name)
                if month:
                    date = f"{year:04d}-{month:02d}-{day:02d}"
            break

    schedule_start = None
    for i, line in enumerate(lines):
        if line == "Event Schedule":
            title_lines = []
            j = i + 1
            while j < len(lines):
                current = lines[j]
                if current.startswith("Perform Location:"):
                    location = current.split("Perform Location:", 1)[1].strip()
                    break
                if "Perform Location:" in current:
                    before, _, after = current.partition("Perform Location:")
                    if before.strip():
                        title_lines.append(before.strip())
                    location = after.strip()
                    break
                if current.startswith("WA FBLA SBLC") or current.startswith("Generated by Blue Panda"):
                    break
                if current in {"Setup Perform End", "Perform End", "Setup Perform"}:
                    break
                title_lines.append(current)
                j += 1
            event_name = " ".join(title_lines).strip()
        if line in {"Setup Perform End", "Perform End", "Setup Perform"}:
            schedule_start = i + 1
            break

    if not event_name or schedule_start is None:
        return None, []

    rows: list[dict] = []
    i = schedule_start
    while i < len(lines):
        current = lines[i]
        if current.startswith("WA FBLA SBLC") or current.startswith("Generated by Blue Panda"):
            break
        if current.startswith("Event When:") or current == "Event Schedule":
            break
        if current.startswith("BREAK"):
            i += 1
            continue

        school = current
        i += 1
        if i >= len(lines):
            break
        region = lines[i]
        i += 1

        names: list[str] = []
        time_tokens: list[str] = []
        while i < len(lines):
            candidate = lines[i]
            if candidate.startswith("BREAK") or candidate.startswith("WA FBLA SBLC") or candidate.startswith("Generated by Blue Panda"):
                break
            if candidate.startswith("Event When:") or candidate == "Event Schedule":
                break

            candidate_prefix, candidate_times = _split_names_and_times(candidate)
            if candidate_times:
                if candidate_prefix:
                    names.append(candidate_prefix)
                time_tokens = candidate_times
                i += 1
                break

            names.append(candidate)
            i += 1

        if not time_tokens:
            continue

        times = {"date": date, "prep": None, "setup": None, "perform": None}
        if len(time_tokens) == 3:
            times["setup"] = normalize_time(time_tokens[0])
            times["perform"] = normalize_time(time_tokens[1])
            times["end"] = normalize_time(time_tokens[2])
        elif len(time_tokens) == 2:
            times["perform"] = normalize_time(time_tokens[0])
            times["end"] = normalize_time(time_tokens[1])
        else:
            times["perform"] = normalize_time(time_tokens[0])

        rows.append({
            "school": school,
            "event": event_name,
            "names": names,
            "times": times,
            "location": location,
        })

    return None, rows


def parse_page(text: str, year: int) -> tuple[str | None, list[dict]]:
    lines = [clean_line(line) for line in text.splitlines() if clean_line(line)]
    if not lines:
        return None, []

    if any(line.startswith("Event When:") for line in lines):
        return _parse_event_schedule_page(lines, year)

    school = None
    for i, line in enumerate(lines[:8]):
        if line == "Event Schedule" and i + 1 < len(lines):
            school = lines[i + 1]
            break

    header_idx = None
    header_tokens = None
    for i, line in enumerate(lines):
        if line.startswith("Date "):
            header_idx = i
            header_tokens = line.split()[1:]
            break

    if not school or header_idx is None or not header_tokens:
        return school, []

    rows: list[dict] = []
    i = header_idx + 1
    while i < len(lines):
        line = lines[i]
        if line == "No Scheduled Entries":
            break
        if line == "WA FBLA SBLC 2026" or HEADER_RE.match(line):
            i += 1
            continue

        block: list[str] = []
        while i < len(lines):
            current = lines[i]
            if (
                current.startswith("Prep Location:")
                or current.startswith("Setup Location:")
                or current.startswith("Perform Location:")
                or current == "No Scheduled Entries"
                or current == "WA FBLA SBLC 2026"
                or HEADER_RE.match(current)
            ):
                break
            block.append(current)
            i += 1

        while i < len(lines) and (
            lines[i].startswith("Prep Location:")
            or lines[i].startswith("Setup Location:")
            or lines[i].startswith("Perform Location:")
        ):
            i += 1

        if not block:
            i += 1
            continue

        date_row_idx = None
        before = None
        date_token = None
        time_tokens = None
        for j, candidate in enumerate(block):
            m = re.search(r"\b(\d{1,2}/\d{1,2})\b\s+(.*)$", candidate)
            if not m:
                continue
            tail = m.group(2).strip()
            found_times = TIME_RE.findall(tail)
            if len(header_tokens) == 2 and len(found_times) >= 2:
                date_row_idx = j
                before = candidate[: m.start(1)].strip()
                date_token = m.group(1)
                time_tokens = found_times[:2]
                break
            if len(header_tokens) == 3 and len(found_times) >= 3:
                date_row_idx = j
                before = candidate[: m.start(1)].strip()
                date_token = m.group(1)
                time_tokens = found_times[:3]
                break

        if date_row_idx is None or before is None or date_token is None or time_tokens is None:
            continue

        names = block[date_row_idx + 1 :]

        event, inline_name = split_event_and_inline_name(before)
        all_names = []
        if inline_name:
            all_names.append(inline_name)
        all_names.extend(name for name in names if name)

        times = {"date": normalize_date(date_token, year), "prep": None, "setup": None, "perform": None}
        if header_tokens == ["Prep", "Perform"]:
            times["prep"] = normalize_time(time_tokens[0])
            times["perform"] = normalize_time(time_tokens[1])
        elif header_tokens == ["Setup", "Perform"]:
            times["setup"] = normalize_time(time_tokens[0])
            times["perform"] = normalize_time(time_tokens[1])
        elif header_tokens == ["Prep", "Setup", "Perform"]:
            times["prep"] = normalize_time(time_tokens[0])
            times["setup"] = normalize_time(time_tokens[1])
            times["perform"] = normalize_time(time_tokens[2])
        else:
            for idx, value in enumerate(time_tokens):
                if idx == 0:
                    times["prep"] = normalize_time(value)
                elif idx == 1:
                    times["setup"] = normalize_time(value)
                elif idx == 2:
                    times["perform"] = normalize_time(value)

        rows.append({
            "school": school,
            "event": event,
            "names": all_names,
            "times": times,
        })

    return school, rows


def extract(pdf_path: Path, year: int = 2026) -> tuple[list[dict], list[dict]]:
    flat: list[dict] = []
    grouped: defaultdict[str, list] = defaultdict(list)

    reader = PdfReader(str(pdf_path))
    for page in reader.pages:
        text = page.extract_text() or ""
        school, rows = parse_page(text, year)
        if not rows:
            continue
        flat.extend(rows)
        if school:
            grouped[school].extend({
                "event": row["event"],
                "names": row["names"],
                "times": row["times"],
            } for row in rows)
        else:
            for row in rows:
                grouped[row["school"]].append({
                    "event": row["event"],
                    "names": row["names"],
                    "times": row["times"],
                })

    grouped_json = [
        {"school": school, "entries": entries}
        for school, entries in sorted(grouped.items(), key=lambda kv: kv[0].lower())
    ]
    return flat, grouped_json


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract FBLA competition schedule PDF into JSON.")
    parser.add_argument("pdf", help="Path to the schedule PDF")
    parser.add_argument("--year", type=int, default=2026, help="Year to apply to MM/DD dates")
    parser.add_argument("--flat-out", default="competition_schedule_flat.json", help="Output path for flat JSON")
    parser.add_argument("--grouped-out", default="competition_schedule_grouped.json", help="Output path for grouped JSON")
    args = parser.parse_args()

    pdf_path = Path(args.pdf)
    flat, grouped = extract(pdf_path, year=args.year)

    Path(args.flat_out).write_text(json.dumps(flat, indent=2, ensure_ascii=False), encoding="utf-8")
    Path(args.grouped_out).write_text(json.dumps(grouped, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Wrote {len(flat):,} flat rows to {args.flat_out}")
    print(f"Wrote {len(grouped):,} grouped schools to {args.grouped_out}")


if __name__ == "__main__":
    main()
